# Generated by Django 3.1.6 on 2021-03-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_id', models.CharField(max_length=10, null=True)),
                ('centre_name', models.CharField(max_length=200, null=True)),
                ('state_name', models.CharField(max_length=200, null=True)),
                ('district_name', models.CharField(max_length=200, null=True)),
                ('block_name', models.CharField(max_length=200, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('timing_from', models.CharField(max_length=20)),
                ('timing_to', models.CharField(max_length=20)),
                ('fee_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=50, null=True)),
            ],
        ),
    ]
