# Generated by Django 3.1.6 on 2021-03-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccine_centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=6, null=True, unique=True)),
                ('session_date', models.CharField(max_length=20, null=True)),
                ('avalable_capacity', models.CharField(max_length=10, null=True)),
                ('slot', models.CharField(max_length=20, null=True)),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccine_centre.vaccinecentre')),
            ],
        ),
    ]
