# Generated by Django 3.1.6 on 2021-04-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateField(),
        ),
    ]
