# Generated by Django 3.1.6 on 2021-05-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210415_1550'),
        ('session', '0002_auto_20210415_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=2, null=True)),
                ('date_of_dose', models.DateField()),
                ('vaccine_name', models.CharField(choices=[('Covishield', 'Covishield'), ('Covaxin', 'Covaxin')], max_length=50, null=True)),
                ('vaccinated_by', models.CharField(max_length=50)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.beneficiary')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.session')),
            ],
        ),
    ]
