# Generated by Django 3.1.6 on 2021-03-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='block_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='centre_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='centre_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='state_name',
        ),
    ]
