# Generated by Django 3.1.6 on 2021-03-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210314_1301'),
        ('appointment', '0004_auto_20210321_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.beneficiary'),
        ),
    ]
