# Generated by Django 3.1.6 on 2021-03-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        ('appointment', '0005_appointment_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.session'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dose',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='session_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
