# Generated by Django 3.1.6 on 2021-04-15 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20210322_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
