# Generated by Django 3.1.6 on 2021-05-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='complete',
        ),
    ]
