# Generated by Django 3.1.6 on 2021-03-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210313_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='diagonised_with_covid',
            field=models.BooleanField(default=False),
        ),
    ]
